#FROM tiangolo/uwsgi-nginx-flask:python3.6-alpine3.7
#
#WORKDIR /app
#
#RUN apk update && apk add --no-cache --virtual .build-deps \
#    gcc \
#    g++ \
#    make \
#    libffi-dev \
#    libpq postgresql-dev && \
#    wget -c https://ftp.postgresql.org/pub/pgadmin/pgadmin4/v2.1/pip/pgadmin4-2.1-py2.py3-none-any.whl  -O pgadmin4-2.1-py2.py3-none-any.whl && \
#    pip install pgadmin4-2.1-py2.py3-none-any.whl && \
#    apk del .build-deps && \
#    apk add postgresql-plpython2 postgresql-plpython2-contrib
#
