version: '3.1'
services:
    walden_db:
        hostname: walden_db
        build: ./db
        image: walden-db 
        #privileged: true
        environment:
            - POSTGRES_PASSWORD=pgpass
        ports:
            - "5433:5432"
        volumes:
            - ./db/initdb:/walden-entrypoint-initdb.d
            - /srv/code/walden/walden:/walden
        networks:
            - pgadmin
    walden_web:
        hostname: walden_frontend
        build: ./web
        expose:
            - 80
        environment:
            - VIRTUAL_HOST=*.cometo.vegas 
        networks:
            - nginx-proxy
#volumes:
#    web-root:
#
networks:
   pgadmin:
       external: true
   nginx-proxy:
       external: true
