CREATE SCHEMA walden;
CREATE SCHEMA walden_history;

GRANT ALL ON SCHEMA walden TO walden;
GRANT ALL ON SCHEMA walden_history TO walden;

ALTER DEFAULT PRIVILEGES IN SCHEMA walden
GRANT ALL ON TABLES TO walden;
ALTER DEFAULT PRIVILEGES IN SCHEMA walden_history
GRANT ALL ON TABLES TO walden;

ALTER DEFAULT PRIVILEGES IN SCHEMA walden
GRANT USAGE ON SEQUENCES TO walden;
ALTER DEFAULT PRIVILEGES IN SCHEMA walden_history
GRANT USAGE ON SEQUENCES TO walden;

ALTER DEFAULT PRIVILEGES IN SCHEMA walden
GRANT EXECUTE ON FUNCTIONS TO walden;
ALTER DEFAULT PRIVILEGES IN SCHEMA walden_history
GRANT EXECUTE ON FUNCTIONS TO walden;

ALTER DEFAULT PRIVILEGES IN SCHEMA walden
GRANT USAGE ON TYPES TO walden;
ALTER DEFAULT PRIVILEGES IN SCHEMA walden_history
GRANT USAGE ON TYPES TO walden;
