EXTENSION = walden_taxonomy            # the extensions name
DATA = sql/walden_taxonomy--0.1.0.sql  # script files to install

# postgres build stuff
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
