EXTENSION = walden_webdev           # the extensions name
DATA = sql/walden_webdev--0.0.1.sql  # script files to install

# postgres build stuff
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
