EXTENSION = walden_sites           # the extensions name
DATA = sql/walden_sites--0.0.1.sql  # script files to install

# postgres build stuff
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
